# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  on_success: change # send a notification when the build status changes
  on_failure: always # always send a notification
